version: '3.8'
services:
  etl_service:
    build: .
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - warehouse_db
      
  warehouse_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DWH_DB_NAME}
      - POSTGRES_USER=${DWH_USER}
      - POSTGRES_PASSWORD=${DWH_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data 